function wcstart()

ProjectPicker = figure('Name', 'Pick A Project', ...
            'NumberTitle', 'off', ...
            'Units', 'normal',...
            'Position', [.33 .33 .2 .33]);

PP.textChooser = uicontrol('Style','text', ...
			'Units','normalized',...
			'Position',[.25 .86 .5 .04],...
			'String','SELECT A PROJECT',...
			'HorizontalAlignment','center',...
            'BackgroundColor',ones(1,3)*0.8,...
		    'Visible','on'); 

        
try 
    pathlocation = textread('C:\Users\manub\OneDrive\Documents\MATLAB\Whole Cell Standard Program\datalocation.txt','%s','delimiter', ',');  
    MyList = dir(pathlocation{1});
    MyProjects = {MyList.name};
    MyProjects = MyProjects(3:end);
    PP.pathlocation = pathlocation{1};
    
catch
    disp('Unable to find datalocation.txt ... create a text file with the path')
    MyProjects = {' '};
end

PP.Chooser = uicontrol('Style','popupmenu', ...
			'Units','normalized',...
			'Position',[.25 .81 .5 .04],...
			'String',MyProjects,...
			'HorizontalAlignment','center',...
            'BackgroundColor',ones(1,3),...
		    'Visible','on'); 

PP.OK = uicontrol('Style','pushbutton', ...
			'Units','normalized',...
			'Position',[.25 .73 .5 .05],...
			'String','Select',...
			'HorizontalAlignment','center',...
            'callback',@OK, ... 
		    'Visible','on');
        
set(ProjectPicker,'Userdata',PP);        
               
function OK(varargin)
ProjectPicker = get(varargin{1}, 'parent');       
PP = get(ProjectPicker,'Userdata');
Projects = get(PP.Chooser,'String');
ProjectSelected = get(PP.Chooser,'value');


RawDatafolder = {[PP.pathlocation '\' Projects{ProjectSelected} '\ZDATA_RAW'],[PP.pathlocation '\' Projects{ProjectSelected} '\EDATA_RAW']};
MatDatafolder = {[PP.pathlocation '\' Projects{ProjectSelected} '\ZDATA_MAT'],[PP.pathlocation '\' Projects{ProjectSelected} '\EDATA_MAT']};

setupGUInew(RawDatafolder, MatDatafolder);
