function LeakFit(varargin)
if nargin==0
    InitializeGUI;
elseif ischar(varargin{1}) % INVOKE NAMED SUBFUNCTION OR CALLBACK
    try
        if (nargout)
            [varargout{1:nargout}] = feval(varargin{:}); % FEVAL switchyard
        else
            feval(varargin{:}); % FEVAL switchyard
        end
    catch
        rethrow(lasterror);
    end
end

function InitializeGUI()
HGUI2.HFigure = figure('Name','Fancy Leak Subtraction', ...
		'NumberTitle', 'off', ...
		'Units', 'normal',...
		'Position', [.01 .33 .66 .60],...
		'UserData', zeros(4,30),'keypressfcn',@(obj, evd) keystroke(obj, evd));			% FInfo (Has Handle Info and Sweep Info)
HGUI2.AxLkfit = axes('box', 'on', 'Position', [.04 .55 .75 .4]);
HGUI2.AxLkFitSub = axes('box', 'on', 'Position', [.445 0.04  .345 .4]);
HGUI2.AxLkSub = axes('box', 'on', 'Position', [0.04 .04 .345 .4]);


%Size constants (in normalized units)
LH = 0.03;  %height per line
S  = 0.005;  %spacer
% ST = 0.005;
SS = 0.01;
AxW = 0.8;
BW  = (1-AxW)/4-1.25*S;

HGUI2.lbloffset = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S .95 BW LH],'string','Offset:');
HGUI2.offset = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+BW .95 BW LH],'string','','CallBack','ChangeFit');
HGUI2.lbllambda = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95 BW LH],'string','Lambda:');
HGUI2.lambda = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95 BW LH],'string','','CallBack','ChangeFit');
myColor = [0.2 0.2 0.2];
% ----------------------------------
HGUI2.lblP2 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-LH-SS BW*2+S LH],'string','PULSE 2', ...
            'FontWeight','bold', 'BackgroundColor',myColor, ...
            'ForegroundColor',1-myColor);        
HGUI2.lblP2offset = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-LH-SS BW LH],'string','Offset:');
HGUI2.P2offset = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-LH-SS BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP2a0 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-2*(LH+SS) BW LH],'string','Amp0');
HGUI2.P2a0 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-2*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP2tau0 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-2*(LH+SS) BW LH],'string','Tau0');
HGUI2.P2tau0 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-2*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP2a1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-3*(LH+SS) BW LH],'string','Amp1');
HGUI2.P2a1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-3*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP2tau1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-3*(LH+SS) BW LH],'string','Tau1');
HGUI2.P2tau1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-3*(LH+SS) BW LH],'string','','CallBack','ChangeFit');
% ----------------------------------        
HGUI2.lblP3 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-4*(LH+SS) BW*2+S LH],'string','PULSE 3', ...
            'FontWeight','bold', 'BackgroundColor',myColor, ...
            'ForegroundColor',1-myColor);        
HGUI2.lblP3offset = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-4*(LH+SS) BW LH],'string','Offset:');
HGUI2.P3offset = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-4*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP3a0 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-5*(LH+SS) BW LH],'string','Amp0');
HGUI2.P3a0 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-5*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP3tau0 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-5*(LH+SS) BW LH],'string','Tau0');
HGUI2.P3tau0 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-5*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP3a1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-6*(LH+SS) BW LH],'string','Amp1');
HGUI2.P3a1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-6*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP3tau1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-6*(LH+SS) BW LH],'string','Tau1');
HGUI2.P3tau1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-6*(LH+SS) BW LH],'string','','CallBack','ChangeFit');
                
% ----------------------------------        
HGUI2.lblP4 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-7*(LH+SS) BW*2+S LH],'string','PULSE 4', ...
            'FontWeight','bold', 'BackgroundColor',myColor, ...
            'ForegroundColor',1-myColor);        
HGUI2.lblP4offset = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-7*(LH+SS) BW LH],'string','Offset:');
HGUI2.P4offset = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-7*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP4a0 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-8*(LH+SS) BW LH],'string','Amp0');
HGUI2.P4a0 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-8*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP4tau0 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-8*(LH+SS) BW LH],'string','Tau0');
HGUI2.P4tau0 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-8*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP4a1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-9*(LH+SS) BW LH],'string','Amp1');
HGUI2.P4a1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-9*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.lblP4tau1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-9*(LH+SS) BW LH],'string','Tau1');
HGUI2.P4tau1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-9*(LH+SS) BW LH],'string','','CallBack','ChangeFit');

HGUI2.BAutofit = uicontrol('Style','pushbutton', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-10*(LH+SS) 2*BW+S 1*LH],'string','Auto Fit','CallBack','AutoFit');
% HGUI2.BWrite = uicontrol('Style','pushbutton', 'Units','normalized',...
% 			'Position',[AxW+S*3+2*BW .95-10*(LH+SS) 2*BW+S 1*LH],'string','WriteData','CallBack','WriteData');


HGUI2.BRestore = uicontrol('Style','pushbutton', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-10*(LH+SS) 2*BW+S 1*LH],'string','RestoreDefaultParams','CallBack','RestoreDefaultParams');

HGUI2.lblError = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-11*(LH+SS) 2*BW+S 1*LH],'string','ERROR:  ', ...            
            'FontWeight','bold', 'BackgroundColor',myColor, ...
            'ForegroundColor',1-myColor);
HGUI2.Error = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-11*(LH+SS) 2*BW+S 1*LH],'ForegroundColor','red','FontWeight','bold','string','0');
% ---------------------------------
HGUI2.lblT1 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-12*(LH+SS) BW 1*LH],'string','T1:  ' ...            
            );
HGUI2.T1 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-12*(LH+SS) BW 1*LH],'callback','ChangeFit');

HGUI2.lblT2 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-12*(LH+SS) BW 1*LH],'string','T2:  ' ...            
            );
HGUI2.T2 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-12*(LH+SS) BW 1*LH],'CallBack','ChangeFit');

HGUI2.lblT3 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-13*(LH+SS) BW 1*LH],'string','T3:  ' ...            
            );
HGUI2.T3 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*2+1*BW .95-13*(LH+SS) BW 1*LH],'callback','ChangeFit');

HGUI2.lblT4 = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-13*(LH+SS) BW 1*LH],'string','T4:  ' ...            
            );
HGUI2.T4 = uicontrol('Style','edit', 'Units','normalized',...
			'Position',[AxW+S*4+3*BW .95-13*(LH+SS) BW 1*LH],'CallBack','ChangeFit');
HGUI2.lblMask = uicontrol('Style','text', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-14*(LH+SS) 4*BW+3*S 1*LH],'string','Mask  ', ...            
            'FontWeight','bold', 'BackgroundColor',myColor, ...
            'ForegroundColor',1-myColor);
HGUI2.Mask = uicontrol('Style','listbox', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-18*(LH+SS) 4*BW+3*S 5*LH-S]);
HGUI2.MaskAdd = uicontrol('Style','pushbutton', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-19*(LH+SS) 2*BW+S 1*LH],'string','AddMask','CallBack','AddMask');
HGUI2.MaskDel = uicontrol('Style','pushbutton', 'Units','normalized',...
			'Position',[AxW+S*3+2*BW .95-19*(LH+SS) 2*BW+S 1*LH],'string','DelMask','CallBack','DelMask');       

% HGUI2.Filter = uicontrol('Style','pushbutton', 'Units','normalized',...
% 			'Position',[AxW+S*1+0*BW .95-20*(LH+SS) 2*BW+S 1*LH],'string','FilterTrace','CallBack','FilterTrace');        


        
HGUI2.BWrite = uicontrol('Style','pushbutton', 'Units','normalized',...
			'Position',[AxW+S*1+0*BW .95-21*(LH+SS) 2*BW+S 1*LH],'string','WriteData','CallBack','WriteData');        

%% store GUI infomation of HFleakfit        
HFleakfit = gcf;
FInfo2.HGUI2 = HGUI2;
set(HFleakfit, 'UserData',FInfo2);
setappdata(0, 'HFleakfit', HFleakfit);
% To retrieve these infomation, use:
% HFleakfit = getappdata(0, 'HFleakfit');
% FInfo2 = get(HFleakfit, 'UserData');
setupleakfitGUI()